/** PRD §11.1 baseline (normative snapshot; live MySQL may grow after). */
export const PRD_BASELINE_TOTAL = 4653;

export const PRD_BASELINE_BY_YEAR: Record<number, number> = {
  2022: 753,
  2023: 1458,
  2024: 912,
  2025: 913,
  2026: 617,
};

export const BUG_BUDGET_COLUMNS = [
  'id',
  'jira_key',
  'project',
  'summary',
  'linked_issues',
  'has_linked_test_execution',
  'tester_assignee',
  'test_engineer_assignee',
  'assignee',
  'engineer_assignee',
  'assignee_final',
  'qa_checker',
  'tested_by',
  'owner',
  'reporter',
  'creator',
  'labels',
  'status',
  'issue_type',
  'final_issue_type',
  'priority',
  'severity_issue',
  'sprint',
  'status_category',
  'status_category_changed',
  'created_date',
  'start_date',
  'begin_date',
  'due_date',
  'end_date',
  'chart_date_first_response',
  'actual_start',
  'actual_end',
  'last_synced_at',
  'story_point_estimate',
  'story_points',
  'epic_link',
  'epic_name',
  'parent',
  'parent_link',
  'epic_level_epic',
  'story_task_level_epic_name',
  'parent_epic_layer_2_key',
  'parent_epic_key',
  'final_epic_name',
  'linked_parent_epic_info',
  'pic_story_task_link_summary',
  'epic_task_story_name_summary',
  'components',
  'fix_versions',
  'is_open',
  'time_spent_seconds',
  'progress_percentage',
  'time_to_resolution_hours',
  'service_feature',
  'service_feature_final',
  'created_year',
  'created_num_month',
  'created_month_alpha',
  'first_response_month',
  'closed_month',
  'closed_year',
  'closed_alpha_month',
  'quarter',
  'first_response_age_days',
  'defect_age_days',
  'defect_age_bucket',
  'defect_count',
  'bug_count',
  'reports',
  'pic_report',
  'ac_related_labels',
  'issue_level_type_layer_1',
  'issue_level_layer_2_type',
  'final_issue',
  'epic_final_issue_type',
  'real_project',
  'bug_cost',
  'raw_jira_data',
  'updated_date',
  'resolved_date',
  'description',
  'created_at',
  'updated_at',
] as const;

export type BugBudgetColumn = (typeof BUG_BUDGET_COLUMNS)[number];

export const JSON_COLUMNS = new Set<BugBudgetColumn>([
  'linked_issues',
  'labels',
  'components',
  'fix_versions',
  'ac_related_labels',
  'raw_jira_data',
]);

export const BOOL_COLUMNS = new Set<BugBudgetColumn>([
  'has_linked_test_execution',
  'is_open',
]);

export const DATE_ONLY_COLUMNS = new Set<BugBudgetColumn>([
  'start_date',
  'begin_date',
  'due_date',
  'end_date',
]);
